#!/usr/bin/env python

import os
import sys
import logging
import argparse

import rdflib
from amara.thirdparty import httplib2, json

from versa import I, VERSA_BASEIRI
from versa import util
from versa.driver import memory

from bibframe import BFZ, BFLC, register_service
from bibframe.reader import marc, marcxml, statsgen
from bibframe.writer import rdf


#PREFIXES = {u'ma': 'http://www.loc.gov/MARC21/slim', u'me': 'http://www.loc.gov/METS/'}

#XXX: This refusal of rdflib to serialize without NS bindings set is really f@cking annoying [...to be fair seems not a problem for turtle output

BFNS = rdflib.Namespace(BFZ)
BFCNS = rdflib.Namespace(BFZ + 'cftag/')
BFDNS = rdflib.Namespace(BFZ + 'dftag/')
VNS = rdflib.Namespace(VERSA_BASEIRI)


def run(inputs=None, base=None, out=None, config=None, verbose=False, mods=None):
    if config is None:
        config = {}
    else:
        config = json.load(config)
    logger = logging.getLogger('marc2bfrdf')
    if verbose:
        logger.setLevel(logging.DEBUG)

    for mod in mods or []:
        __import__(mod, globals(), locals(), [], -1)
    from bibframe import g_services

    #if stats:
    #    register_service(statsgen.statshandler)

    ids = marc.idgen(base)
    m = memory.connection()
    g = rdflib.Graph()
    g.bind('bf', BFNS)
    g.bind('bfc', BFCNS)
    g.bind('bfd', BFDNS)
    g.bind('v', VNS)

    def postprocess(rec):
        rdf.process(m, g, logger=logger)
        m.create_space()

    #Initialize auxiliary services (i.e. plugins)
    plugins = []
    for pc in config[u'plugins']:
        try:
            plugins.append(g_services[pc[u'id']](
                config=pc,
                logger=logger,
            )
            )
        except KeyError:
            raise Exception(u'Unknown plugin {0}'.format(pc[u'id']))

    for inf in inputs:
        sink = marc.record_handler(m, idbase=base, plugins=plugins, ids=ids, postprocess=postprocess, logger=logger)
        marcxml.parse_marcxml(inf, sink)

    out.write(g.serialize(format="turtle"))
    for plugin in plugins:
        plugin.close()
    return


if __name__ == '__main__':
    #marc2bfrdf -v -o /tmp/lcout.ttl -s /tmp/lcout.stats.js scratch/unpacked/lc-sample-files-20120725.xml 2> /tmp/lcout.log
    #parser = argparse.ArgumentParser(prog="bootstrap", add_help=False)
    parser = argparse.ArgumentParser()
    parser.add_argument('inputs', type=argparse.FileType('r'), metavar='inputs', nargs='+',
                        help='One or more MARC/XML files to be parsed and converted to BIBFRAME RDF')
    parser.add_argument('-o', '--out', type=argparse.FileType('w'), default=sys.stdout,
        help='file where output should be written '
             '(default: write to stdout)')
    parser.add_argument('-c', '--config', type=argparse.FileType('r'),
        help='file containing config in JSON format')
    #parser.add_argument('-s', '--stats', type=argparse.FileType('w'),
    #    help='file where statistics output should be written in JSOn format')
    #parser.add_argument('-c', '--config', type=argparse.FileType('r'),
    #    help='config, a Versa file whose config (in the @docheader) should be used to parse the rest')
    parser.add_argument('-b', '--base', metavar="IRI", #dest="base",
        help='Base IRI to be used for creating resources.')
    parser.add_argument('--mod', metavar="PYMODULE", nargs='*',
        help='Python module to be imported in order to register plugins.')
    parser.add_argument('-v', '--verbose', action='store_true',
        help='whether to show additional messages and information')
    #
    args = parser.parse_args()

    run(inputs=args.inputs, base=args.base, out=args.out, config=args.config, verbose=args.verbose, mods=args.mod)
    for f in args.inputs: f.close()
    args.out.close()

